jobs:
- job: Windows
  pool:
    vmImage: windows-2019
  steps:
  - script: build-and-test.cmd
  - script: src\deploy-to-artifacts.bat
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: artifacts/Deploy
      artifactName: Desktop
- job: Linux
  pool:
    vmImage: ubuntu-16.04
  steps:
  - script: ./build-and-test.sh
