name: CI

on: [push, pull_request]

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        configuration: [Debug, Release]
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.200'
    - name: Build and test
      shell: pwsh
      run: |
        $shellExt = if ($IsWindows) { "cmd" } else { "sh" }
        & ./build-and-test.$shellExt --configuration ${{ matrix.configuration }}

  pack:
    needs: [build]
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.200'
    - run: .\build-and-test.cmd -c Release -notest
    - run: .\pack.cmd -c Release
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ env.extension_artifact_name }}
        path: artifacts/publish/${{ env.extension_artifact_name }}
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ env.server_artifact_name }}
        path: artifacts/publish/${{ env.server_artifact_name }}
